name: Code for Portland
markdown: redcarpet
pygments: true
exclude: [node_modules, vendor, '*.json', 'Gemfile*', 'Gruntfile.*']
permalink: /:categories/:year/:month/:title
paginate: 10

modernizr: "/bower_components/modernizr/modernizr.js"
js:
  - '/bower_components/jquery/dist/jquery.min.js'
  - '/bower_components/retina.js/src/retina.js'
  - '/bower_components/knockout.js/knockout.js'
  - '/bower_components/foundation/js/foundation/foundation.js'
  - '/bower_components/foundation/js/foundation/foundation.topbar.js'
  - '/bower_components/foundation/js/foundation/foundation.orbit.js'
  - '/assets/js/app.js'
css:
  - '/assets/css/app.css'
